spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CCD_DB
    username: admin
    password: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update